### ISSUE TITLE
A questions about data processing.

### ISSUE THREAD

**Issue by UM2020-create** [luosongcug/HLRTccfs#1]
Hi Dr. Luo,

    Thanks for sharing your code which works efficiently in removing interference from CCFs of ambient noise. In this code, a CCF is processed twice when each station was taken as a virtual source separately. Then the two processed CCFs will be averaged if their correlation coefficient is higher than a threshold. I want to ask how to process the data when its correlation coefficient is lower than the coefficient threshold (like 0.5)? For my datasets, their are only one third of them is acceptable under this condition. Should I discard the rest of CCFs? Or reduce the threshold? Or change the slowness range to recalculate? Hope to receive your suggestion. And please correct me if their are any mistakes in my understanding. Thanks!

Regards,
JT

**Comment by luosongcug** [comment]
Hi JT,

Based on our experience, having more stations (which usually leads to denser distances) tends to result in smoother CCFs and lower correlation coefficients with HLRT. The reason behind this observation is that, in the 3D heterogeneous structure of the real world, the denser the stations, the more challenging it becomes to achieve sparse solutions using HLRT.

To address the issue of low correlation coefficients, Prof. Yao Huajian suggested a solution during a group meeting. The suggestion is to calculate correlation coefficients using windowed signals, typically surface waves, instead of the entire waveforms of CCFs.

One of Prof. Yao's students implemented this approach, and it showed some improvements in the correlation coefficients.

I hope this answers your question.

Sincerely,
Song Luo

**Comment by UM2020-create** [comment]
Thanks for your reply and suggestion. They are very helpful!
